"""add_status_check_constraint

Revision ID: 00581fcd8b47
Revises: 12f074c2cc50
Create Date: 2025-12-06 23:57:12.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00581fcd8b47'
down_revision: Union[str, None] = '12f074c2cc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add CHECK constraint for status field
    op.create_check_constraint(
        'submissions_status_check',
        'submissions',
        "status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE', 'ERROR')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the CHECK constraint
    op.drop_constraint('submissions_status_check', 'submissions', type_='check')
    # ### end Alembic commands ###

