"""add_very_easy_difficulty

Revision ID: 12f074c2cc50
Revises: aba1fde81f82
Create Date: 2025-12-03 00:42:03.199725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f074c2cc50'
down_revision: Union[str, None] = 'aba1fde81f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old constraint
    op.drop_constraint('problems_difficulty_check', 'problems', type_='check')
    # Add the new constraint with 'Very Easy' included
    op.create_check_constraint(
        'problems_difficulty_check',
        'problems',
        "difficulty IN ('Very Easy', 'Easy', 'Medium', 'Hard')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new constraint
    op.drop_constraint('problems_difficulty_check', 'problems', type_='check')
    # Restore the old constraint
    op.create_check_constraint(
        'problems_difficulty_check',
        'problems',
        "difficulty IN ('Easy', 'Medium', 'Hard')"
    )
    # ### end Alembic commands ###
