"""add bookmarked_problems table

Revision ID: 66a01fac575d
Revises: 6a424a4dc3ed
Create Date: 2025-12-12 15:16:25.364286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a01fac575d'
down_revision: Union[str, None] = '6a424a4dc3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarked_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problem_bookmark')
    )
    op.create_index(op.f('ix_bookmarked_problems_problem_id'), 'bookmarked_problems', ['problem_id'], unique=False)
    op.create_index(op.f('ix_bookmarked_problems_user_id'), 'bookmarked_problems', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarked_problems_user_id'), table_name='bookmarked_problems')
    op.drop_index(op.f('ix_bookmarked_problems_problem_id'), table_name='bookmarked_problems')
    op.drop_table('bookmarked_problems')
    # ### end Alembic commands ###
